name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          script: |
            cd /home/ubuntu/ecommerce-django
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            export GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            python manage.py migrate
            cat > /home/ubuntu/ecommerce-django/.env << EOF
            DB_NAME=ecommerce_db
            DB_USER=postgres
            DB_PASSWORD=Sai@1234Db
            DB_HOST=localhost
            DB_PORT=5432
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            EOF
            sudo systemctl restart gunicorn
            sudo apt install nginx -y
            sudo apt install certbot python3-certbot-nginx -y
            sudo bash -c 'cat > /etc/nginx/sites-available/solemate << EOF
            server {
                listen 80;
                server_name solemate.servecounterstrike.com;
                location / {
                    proxy_pass http://127.0.0.1:8000;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                }
            }
            EOF'
            sudo ln -sf /etc/nginx/sites-available/solemate /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl restart nginx
            sudo certbot --nginx -d solemate.servecounterstrike.com --non-interactive --agree-tos -m tejayadav872@gmail.com
            sudo systemctl restart gunicorn
           