name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          script: |
            cd /home/ubuntu/ecommerce-django
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            export GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            python manage.py migrate
            printf 'DB_NAME=ecommerce_db\nDB_USER=postgres\nDB_PASSWORD=Sai@1234Db\nDB_HOST=localhost\nDB_PORT=5432\nAWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}\nAWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}\n' > /home/ubuntu/ecommerce-django/.env
            printf '[Unit]\nDescription=gunicorn daemon\nAfter=network.target\n\n[Service]\nUser=ubuntu\nWorkingDirectory=/home/ubuntu/ecommerce-django\nEnvironmentFile=/home/ubuntu/ecommerce-django/.env\nExecStart=/home/ubuntu/ecommerce-django/venv/bin/gunicorn --workers 3 --bind 0.0.0.0:8000 ecommerce.wsgi:application\n\n[Install]\nWantedBy=multi-user.target\n' | sudo tee /etc/systemd/system/gunicorn.service
            sudo systemctl daemon-reload
            sudo systemctl restart gunicorn
            sudo apt install nginx -y
            sudo apt install certbot python3-certbot-nginx -y
            printf 'server {\n    listen 80;\n    server_name solemate.servecounterstrike.com;\n\n    location /static/ {\n        alias /home/ubuntu/ecommerce-django/staticfiles/;\n    }\n\n    location /media/ {\n        alias /home/ubuntu/ecommerce-django/media/;\n    }\n\n    location / {\n        proxy_pass http://127.0.0.1:8000;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n    }\n}\n' | sudo tee /etc/nginx/sites-available/solemate
            sudo ln -sf /etc/nginx/sites-available/solemate /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl restart nginx
            sudo certbot --nginx -d solemate.servecounterstrike.com --non-interactive --agree-tos -m tejayadav872@gmail.com
            sudo systemctl restart gunicorn